spring:
  application:
    name: notification-service
  datasource:
    url: jdbc:postgresql://notification-database:5432/linkedin-notificationdb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  kafka:
    admin:
      auto-create-topics: true
      fail-fast: true
    bootstrap-servers: kafka-server:9092
    consumer:
      group-id: notification-service-group
      auto-offset-reset: earliest
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
#        spring.json.value.default.type: com.niladri.post_service.event.PostLikeEvent
        spring.json.trusted.packages: com.niladri.*
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 9040
  servlet:
    context-path: /notifications
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://discovery-service:8761/eureka/