spring:
  application:
    name: post-service
  datasource:
    url: jdbc:postgresql://localhost:5432/linkedin-postdb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 9010
  servlet:
    context-path: /posts


