spring:
  application:
    name: user-service
  cache:
    type: redis
    redis:
      time-to-live: 10m
  data:
    redis:
      host: redis-cache
      port: 6379
      ssl:
        enabled: false
  datasource:
    url: jdbc:postgresql://user-database:5432/linkedin-userdb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  servlet:
    context-path: /users
  port: 9020
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://discovery-service:8761/eureka/
jwt:
  secretKey: iuhiuhiuyihg8hohgoihoihoihiohlhlkjhglhkjhlkhlkhioguogh
